# Generated by Django 5.2.7 on 2025-11-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_lead',
        ),
        migrations.AlterField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('Manager', 'Manager'), ('TeamLeader', 'TeamLeader'), ('Admin', 'Admin')], default='employee', max_length=50),
        ),
        migrations.DeleteModel(
            name='TeamLeader',
        ),
    ]
