# Generated by Django 5.2.7 on 2025-10-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
