# Generated by Django 5.2.7 on 2025-11-11 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_phase_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailynotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('Tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
        ),
    ]
