# Generated by Django 5.2.7 on 2025-10-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
