# Generated by Django 5.2.7 on 2025-11-07 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_admin_manager_teamleader_alter_phase_team_leader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_lead',
        ),
        migrations.AddField(
            model_name='phase',
            name='role',
            field=models.CharField(blank=True, default='Design', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='assignphases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(blank=True, default='small', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('Phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='api.phase')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
