# Generated by Django 5.2.7 on 2025-10-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='username',
            new_name='adminuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
