# Generated by Django 5.2.7 on 2025-10-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_username_adminuser_adminuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='adminuser',
            new_name='admin_user',
        ),
    ]
