# Generated by Django 5.2.7 on 2025-11-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_phase_name_remove_team_team_lead_phase_role_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assignphases',
            new_name='phasesassign_to_members',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='priority',
        ),
        migrations.AddField(
            model_name='phase',
            name='progress',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
