# Generated by Django 5.2.7 on 2025-11-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_assignphases_phasesassign_to_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
