# Generated by Django 5.2.7 on 2025-11-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_phase_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phasesassign_to_members',
            name='priority',
        ),
    ]
