# Generated by Django 5.2.7 on 2025-10-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_team_members_alter_team_name_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
