# Generated by Django 5.2.7 on 2025-11-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleader',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
