# Generated by Django 5.2.7 on 2025-10-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_project_end_data_alter_project_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
