# Generated by Django 5.2.7 on 2025-10-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_end_data_project_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='member',
            new_name='members',
        ),
    ]
