# Generated by Django 5.2.7 on 2025-11-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_teamleader_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phasesassign_to_members',
            new_name='teamleader_to_members',
        ),
    ]
