# Generated by Django 5.2.7 on 2025-10-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_member_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, default='planning', max_length=100, null=True),
        ),
    ]
