# Generated by Django 5.2.7 on 2025-11-07 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_phasesassign_to_members_teamleader_to_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='team_leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'role_type': 'TeamLeader'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
