# Generated by Django 5.2.7 on 2025-11-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_phase_team_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
