# Generated by Django 5.2.7 on 2025-10-28 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_team',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
