# Generated by Django 5.2.7 on 2025-11-08 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_phase_team_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='role',
            new_name='Phases',
        ),
        migrations.CreateModel(
            name='TeamLeaderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_self_assigned', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leaders', to='api.teamleader')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_assignments', to='api.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_assignments', to='api.project')),
            ],
        ),
        migrations.DeleteModel(
            name='teamleader_to_members',
        ),
    ]
