# Generated by Django 5.2.7 on 2025-11-08 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_role_phase_phases_teamleaderassignment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='Phases',
            new_name='role',
        ),
    ]
