# Generated by Django 5.2.7 on 2025-10-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_team',
        ),
    ]
