# Generated by Django 5.2.7 on 2025-10-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_user_user_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Task_inform', models.TextField(blank=True, null=True)),
                ('Start_date', models.DateField(auto_now=True)),
                ('deadline', models.DateField(auto_now=True)),
                ('status', models.CharField(blank=True, default='Not Started', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('Task_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
