# Generated by Django 5.2.7 on 2025-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, default='not Started', max_length=100, null=True),
        ),
    ]
