# Generated by Django 5.2.7 on 2025-10-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_task_start_date_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Task_inform',
            new_name='task_inform',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Task_member',
            new_name='task_member',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Task_name',
            new_name='task_name',
        ),
    ]
