# Generated by Django 5.2.7 on 2025-11-08 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_category_description_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
