# Generated by Django 5.2.7 on 2025-11-08 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_manager_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='phase_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cat_phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('phases', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.phase_list')),
            ],
        ),
    ]
