# Generated by Django 5.2.7 on 2025-10-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_start_date_task_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskperformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
        ),
    ]
