# Generated by Django 5.2.7 on 2025-10-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_taskperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='medium'),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, default='open', max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_member',
        ),
        migrations.DeleteModel(
            name='Taskperformance',
        ),
        migrations.AddField(
            model_name='task',
            name='task_member',
            field=models.ManyToManyField(blank=True, to='api.user'),
        ),
    ]
