# Generated by Django 5.2.7 on 2025-11-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_phase_list_cat_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.DeleteModel(
            name='cat_phase',
        ),
        migrations.DeleteModel(
            name='phase_list',
        ),
    ]
