# Generated by Django 5.2.7 on 2025-11-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_project_category_delete_cat_phase_delete_phase_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Category',
            new_name='Categorys',
        ),
    ]
