# Generated by Django 5.2.7 on 2025-10-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_task_priority_task_progress_alter_task_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_member',
            new_name='task_members',
        ),
    ]
