# Generated by Django 5.2.7 on 2025-11-10 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_manager_category_remove_user_categorys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.phase'),
        ),
    ]
