# Generated by Django 5.2.7 on 2025-10-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
