# Generated by Django 5.2.7 on 2025-10-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_project_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='open', max_length=100, null=True)),
                ('process', models.PositiveIntegerField(blank=True, default=0, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('members', models.ManyToManyField(blank=True, to='api.user')),
            ],
        ),
    ]
