# Generated by Django 5.2.7 on 2025-10-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_individualtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtask',
            name='process',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
