# Generated by Django 5.2.7 on 2025-11-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.AlterField(
            model_name='teamleaderassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leaders', to='api.user'),
        ),
        migrations.DeleteModel(
            name='TeamLeader',
        ),
    ]
