# Generated by Django 5.2.7 on 2025-11-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='phase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
