# Generated by Django 5.2.7 on 2025-10-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_individualtask_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualtask',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualtask',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
