# Generated by Django 5.2.7 on 2025-10-31 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_individualtask_enddate_individualtask_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualtask',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='individualtask',
            old_name='startdate',
            new_name='start_date',
        ),
    ]
